server:
  port : 8081

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ppmt
    username: root
    password: root
  jpa:
    hibernate:
      # ddl-auto: create-drop
      ddl-auto: update
  properties:
    hibernate:
      order_inserts: true
      order_updates: true
      generate_statistics: false
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      format_sql: false
      jdbc:
        batch_size: 50
        batch_versioned_data: true
      cache:
        #required - turn on L2 cache.
        use_second_level_cache: true
        #optional - turn on query cache.
        use_query_cache: true
        region:
          #required - classpath to cache region factory.
          factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
      javax:
        persistence:
          sharedCache:
            #required - enable selective caching mode - only entities with @Cacheable annotation will use L2 cache.
            mode: ENABLE_SELECTIVE
    show-sql: true